### PR TITLE
Fix chicken&egg problem

### LINKED ISSUE #5: generateHollowConsumerApi chicken & egg problem 🐣
Given a pristine (e.g. new clone or `git clean`) gradle project with hollow model classes and classes that depend on the generated consumer API, the plugin cannot generate the API.

The plugin depends on a successful compile of the hollow model classes, thus the `generateHollowConsumerApi` task depends on the `build` task. However, the `build` task attempts to compile code that requires generated consumer classes which haven't been generated yet and thus fails.

### PR DESCRIPTION
**Pull request by flore77**
Fixes #5.

Extra:
- cleans also the generated files on `gradle clean` task
- fixes also a small bug regarding `destinationPath`

### CODE REVIEW

**Comment by rpalcolea** [comment]
thoughts on this @toolbear ?

File: src/main/java/com/netflix/nebula/hollow/ApiGeneratorTask.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public void generateApi() throws IOException {
             mapper.initializeTypeState(clazz);
         }
 
-        String apiTargetPath = extension.destinationPath != null && extension.destinationPath.isEmpty() ? extension.destinationPath : buildPathToApiTargetFolder(extension.apiPackageName);
+        String apiTargetPath = !extension.destinationPath.isEmpty() ? extension.destinationPath : buildPathToApiTargetFolder(extension.apiPackageName);
```
Comment (orjan) [inline src/main/java/com/netflix/nebula/hollow/ApiGeneratorTask.java:62]: I stumbled upon this bug today as well.
Would it be easier to separate this bug fix out of the chicken and egg solution?

**Comment by flore77** [comment]
ping @rpalcolea @toolbear
